### ISSUE TITLE
Future of this gem

### ISSUE THREAD

**Issue by moechaieb** [Shopify/transfer_jobs#21]
This gem was meant to extract and abstract away the transfer-jobs step of AF. But as it stands, functionality is still fragmented between the gem and `Shopify/shopify`. We need to decide how to consolidate the code.

@kirs suggested that we move as much as possible of the "Transferring Redis data" concern to this gem, while leaving Podding concerns and the rake task itself in Shopify/shopify.

@Shopify/pods @Shopify/job-patterns Thoughts?

**Comment by kirs** [comment]
My strategy is usually "extract as late as possible", which saved us a lot of time with Iteration - if we extracted it too early, it would have been way more difficult to come up with Iteration v2.

I'd have the same thought for TJ, but based on README it looks like it was extracted for `facebook-commerce`? Can you check if they are still using it?

The future of Redis failovers is unclear (what if we use replication at least outside of core?), if facebook-commerce is not consuming the gem I'd vote to hold off with the extraction. Maybe it's easier to keep the beast in Core for now, especially if you're going to introduce more changes.

**Comment by BoGs** [comment]
I would hold off and extract at the point where there could be multiple potential consumers (ensures you do not build custom solution for one). I took a look at `facebook-commerce` and it is not in their `Gemfile`([link](https://github.com/Shopify/facebook-commerce/blob/master/Gemfile)).

**Comment by moechaieb** [comment]
We have since stopped using this gem completely.

**Comment by kirs** [comment]
Should we archive the repo in this case to have less confusion?
