### ISSUE TITLE
Utility of Recovery Queues

### ISSUE THREAD

**Issue by moechaieb** [Shopify/transfer_jobs#22]
As part of the transfer-jobs step of a failover, we rename each queue in the source region to [`{queue_name}:recovery`](https://github.com/Shopify/transfer_jobs/blob/master/lib/transfer_jobs/redis_queue.rb#L32-L39). This has the following benefits:
1) Workers will stop popping jobs off of those queues, because those `recovery` queues are [not configured to be worked off](https://github.com/Shopify/shopify/blob/master/config/k8s/jobs.yml.erb#L6-L17)
2) In the case of a failed job transfer, TJ knows to resume working from the `recovery` queues,

I'm wondering whether renaming these queues is really the simplest way of achieving (1) and (2):

- Renaming queues is confusing, since some jobs in the delayed queue can technically be scheduled to go back to some of those queues that were renamed... (and [Redis will recreate those queues](https://redis.io/commands/lpush) in the passive region). This is possible because we transfer the delayed queue only after all the other job queues have been transferred.
- This can lead us to a situation where a failed transfer job can lead to the `recovery` being ineffective, since TJ has to check both the recovery queue and the "live" queue to recover. Worse, the retried job can be picked up by a worker, since it's back on a "live" queue (but it won't get worked off since we failover MySQL before transferring jobs and workers skip jobs in pods that are read-only).

Rather, we could do the following:

1) Is already achieved by the database healthcheck before a worker works off a job. **If we can ensure that this is very fast**, this is a viable safeguard against working off jobs in the passive region.
2) TJ can just resume work from the "real" queues when recovering from failures, since those queues will be preserved by (1).

This means we can achieve the same functionality, with simpler code. Alternatively, we can check at runtime if a recovery queue exists when retrying a job, to enqueue the job on the recovery queue rather than the "live" queue, but this seems to introduce complexity rather than reduce it.

Am I missing any historical context on why we need the `recovery` queues? Can we do without them as presented above?

cc @Shopify/pods @Shopify/job-patterns

**Comment by pushrax** [comment]
Your analysis seems sound to me 👍 

The one case I'd watch out for is ensuring TJ can transfer the queue while it's being mutated, if there are any non-atomic operations it might be unsafe. It needs to ensure it can transfer the queue while it's being popped, because 1. is not just about preventing jobs from failing but also about correctness of the transfer. It needs to ensure it can transfer the queue while it's being pushed, since some work might still be running that pushes a new job.

**Comment by hkdsun** [comment]
Related to Justin's comment, I would definitely look over the [Redis SCAN command's guarantees](https://redis.io/commands/scan#scan-guarantees) since that's how we iterate the job queues (would we still iterate all elements if things are being popped at the same time?). Otherwise, simplifying this while achieving better job guarantees sounds great to me.

**Comment by fw42** [comment]
> Am I missing any historical context on why we need the recovery queues? Can we do without them as presented above?

The historical context that I think you are missing is that transfer-jobs is much older than the patch that prevents Resque from popping jobs of a pod's resque-redis if that pod's MySQL is read-only. That feature was added later.

Also keep in mind that there might be use-cases of transfer-jobs in which your assumptions are actually false (for example transfering jobs from one Redis to another but both belong to the same pod and both are in the same location, so there is no read-only database involved that you could rely on; The caching and queuing team has done exactly that just recently, cc @maximebedard).

**Comment by kirs** [comment]
Thanks for the context Flo!

> for example transfering jobs from one Redis to another but both belong to the same pod and both are in the same location, so there is no read-only database involved that you could rely on

That scanario makes sense, but if jobs in source are not getting processed (let's say for migrating between clusters) I don't see why an intermediate queue like `recovery` is necessary.

**Comment by moechaieb** [comment]
Thanks for the context Flo.

@maximebedard what's your opinion on `recovery` queues? And are you going to use TJ for Redis cluster migrations in the future?

**Comment by maximebedard** [comment]
I don't have much context on the recovery queues unfortunately :( But yes your analysis sounds correct 👍 

As for what the we are going to use TJ for, we don't plan on using it to much for cluster migrations. We are done with tier1, and we currently investigating using replication for other tiers. We haven't done much so far, but we are currently investigating alternatives to set-up replication and a "flipper" like mechanism, but this involves quite a bit of work. I'll keep you guys updated with our findings!

**Comment by sirupsen** [comment]
@mac-adam-chaieb while this seems correct (keeping the concerns others have raised here about still needing to support the case where things are getting popped in the case of a failover), what's the ROI you're expecting from this change? Existing monitoring to work?

>  I would definitely look over the Redis SCAN command's guarantees since that's how we iterate the job queues (would we still iterate all elements if things are being popped at the same time?).

I think we just iterate with `LRANGE` and get all the queues `resque:queues`.
